### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by stigersmile** [srclosson/opcua-datasource#12]
Hi Thank you for your toolkit,

But after I run  follow your installation guide and restart my grafana
`
    yarn install to install dependencies
    yarn build | yarn dev to build the plugin
    make build to build the backend component
` 
I didn't see any new datasouce plugin in? (will it plugin automatically or should I manually add some plugin in to grafana?)
my grafana version is V7.1.0

**Comment by dvdjda** [comment]
I got the same, after all no plugin appeared in grafana

**Comment by MrLight** [comment]
You have to add an exception into the configuration to allow loading unsigned plugins.

`allow_loading_unsigned_plugins = grafana-opcua-datasource`

After that the plugin shows up in the list of datasources.

**Comment by alydersen** [comment]
I'm closing this due to lack of response. Thanks to @MrLight for answering.
