### ISSUE TITLE
'grafana-toolkit' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by jkancio** [srclosson/opcua-datasource#6]
Hello,
I tried to build with "yarn build" and I got the error:
 'grafana-toolkit' is not recognized as an internal or external command,

Do I need to use the grafana source in order to build "grafana-opcua-datasource".
Thanks

**Comment by srclosson** [comment]
@jkancio, nope. Just make sure you do a `yarn install --pure-lockfile` prior to doing a `yarn build`
